```{r}
library(tidyverse)
library(ggrepel)
library(RColorBrewer)
```

### 65 and older by Gender and County

```{r}
md_early_voting <- read_csv("https://elections.maryland.gov/press_room/2024_stats/PG24/EarlyVoting%20RAW%20data.csv") %>% filter(AgeGroup == '18-24')

md_early_voting <- md_early_voting %>% mutate(fips_code = case_when(
  COUNTY_CODE < 10 ~ paste0("2400",COUNTY_CODE),
  COUNTY_CODE >= 10 ~ paste0("240",COUNTY_CODE))
) %>% 
  mutate(across(where(is.numeric), ~ replace_na(., 0))) %>% 
  select(-Day2, -Day3, -Day4, -Day5, -Day6, -Day7, -Day8)


md_early_voting_county_gender <- md_early_voting %>% 
  group_by(fips_code, COUNTY_NAME, GENDER_CODE) %>% 
  summarize(total = sum(c_across(starts_with('Day')))) %>% 
  pivot_wider(names_from = GENDER_CODE, values_from = total) %>% 
  rename(UNK = `NA`) %>% 
  mutate(across(where(is.numeric), ~ replace_na(., 0))) %>% 
  mutate(total = M + F + UNK) %>% 
  mutate(pct_male = M/total *100, pct_female = F/total * 100)

# Plot it using geom_point.
md_early_voting_county_gender %>%
  ggplot() +
  geom_point(aes(x=pct_male,y=pct_female, size=total)) +
  geom_text_repel(aes(x=pct_male,y=pct_female, label=COUNTY_NAME), position=position_jitter(width=1,height=1)) +
  labs(
    title="Significant Gender Gaps in 18-24 Maryland Early Voters",
    y = "percent female",
    x = "percent male",
    caption = "source: Maryland State Board of Elections; data covers 1st day"
  ) +
  theme_minimal()
```

### Gender by Congressional District

```{r}
md_early_voting_county_gender_district <- md_early_voting %>% 
  group_by(congressional_district_code, GENDER_CODE) %>% 
  summarize(total = sum(c_across(starts_with('Day')))) %>% 
  pivot_wider(names_from = GENDER_CODE, values_from = total) %>% 
  rename(UNK = `NA`) %>% 
  mutate(across(where(is.numeric), ~ replace_na(., 0))) %>% 
  mutate(total = M + F + UNK) %>% 
  mutate(pct_male = M/total *100, pct_female = F/total * 100)
```

```{r}
md_early_voting_county_gender_district |> 
  select(congressional_district_code, pct_male, pct_female) |> 
  pivot_longer(cols = starts_with("pct_"), names_to = "gender", values_to = "pct") |> 
  ggplot() +
  geom_bar(aes(x=congressional_district_code,weight=pct, fill=gender)) +
  labs(
    title="More Men Voted Early in MD-6",
    y = "percentage",
    x = "congressional district",
    caption = "source: Maryland State Board of Elections; data covers 1st day"
  ) + theme_minimal() + scale_fill_brewer(palette = "Dark2")
```

### Same Day Registration

```{r}
md_same_day <- read_csv("https://elections.maryland.gov/press_room/2024_stats/PG24/SameDayRegistration%20RAW%20data.csv") |> filter(AgeGroup == "18-24")

md_same_day <- md_same_day %>% mutate(fips_code = case_when(
  COUNTY_CODE < 10 ~ paste0("2400",COUNTY_CODE),
  COUNTY_CODE >= 10 ~ paste0("240",COUNTY_CODE))
) %>% 
  mutate(across(where(is.numeric), ~ replace_na(., 0))) %>% 
  select(-NEW_DAY2, -NEW_DAY3, -NEW_DAY4, -NEW_DAY5, -NEW_DAY6, -NEW_DAY7, -NEW_DAY8, -NEW_DAY9) |> 
  select(-ADDRCHG_DAY2, -ADDRCHG_DAY3, -ADDRCHG_DAY4, -ADDRCHG_DAY5, -ADDRCHG_DAY6, -ADDRCHG_DAY7, -ADDRCHG_DAY8)

md_same_day_gender_age <- md_same_day %>% 
  group_by(fips_code, COUNTY_NAME, GENDER_CODE) %>% 
  summarize(total = sum(c_across(starts_with('NEW_DAY')))) %>% 
  pivot_wider(names_from = GENDER_CODE, values_from = total) %>% 
  rename(UNK = `NA`) %>% 
  mutate(across(where(is.numeric), ~ replace_na(., 0))) %>% 
  mutate(total = M + F + UNK) %>% 
  mutate(pct_male = M/total *100, pct_female = F/total * 100)

```

